### ISSUE TITLE
Error: command not found, after `npm install -g "gildas-lormeau/single-file-cli"` 

### ISSUE THREAD

**Issue by gudh** [gildas-lormeau/single-file-cli#10]
First of all, thanks for building this amazing tool, love the chrome extension!

A problem I face when trying to use the CLI tool:

After installing it on mac with `npm install -g "gildas-lormeau/single-file-cli"`, when I try to run `single-file` command, I got error "command not found" 

```sh
➜  ~  npm list -g single-file-cli
/opt/homebrew/lib
└── single-file-cli@ -> ./../../../Users/gudh/.npm/_cacache/tmp/git-cloneIMlDig

➜  ~ single-file
zsh: command not found: single-file
➜  ~ single-file-cli
zsh: command not found: single-file-cli
```

anything I am missing?

**Comment by gudh** [comment]
I tried download `single-file-cli-master` approach, and it works

but `npm install -g "gildas-lormeau/single-file-cli"` approach still doesn't 

```sh
➜  ~ single-file
zsh: command not found: single-file
```

any step I am missing?

**Comment by gudh** [comment]
Update:

After changing command to `npm install -g single-file-cli`, now it works

Problem solved

**Comment by gildas-lormeau** [comment]
@gudh Sorry for the late answer, I'm glad you found the cause of the issue. I updated the instructions. Thank you!

**Comment by gudh** [comment]
@gildas-lormeau cool, thanks for building this amazing tool, love it!

**Comment by gildas-lormeau** [comment]
@gudh You're welcome :)
