### ISSUE TITLE
CLI possible bug

### ISSUE THREAD

**Issue by anotatta** [gildas-lormeau/single-file-cli#103]
Thanks, great addon. I am trying out the cli version to crawl.

Win10 environment, running the single-file cli version 2.045 
Command:
`single-file https://www.wikipedia.org  -browser-wait-until=load  --browser-executable-path "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --crawl-links=true --crawl-inner-links-only=false --crawl-external-links-max-depth=1 --crawl-rewrite-rule="^.*wikipedia.*$"`

Error:
`Unreachable URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js` 
`URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js`
`Stack: Error:`
`Unreachable URL: file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-cli-api.js` 
`at Connection.onFrameNavigated (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/cdp-client.js:306:15)` 
`at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7) `
`at invokeEventListeners (ext:deno_web/02_event.js:801:5)` 
`at dispatch (ext:deno_web/02_event.js:658:9)` 
`at Connection.dispatchEvent (ext:deno_web/02_event.js:1043:12)` 
`at Connection.#onMessage (https://jsr.io/@simple-cdp/simple-cdp/1.8.5/mod.js:205:18)` 
`at WebSocket.<anonymous> (https://jsr.io/@simple-cdp/simple-cdp/1.8.5/mod.js:168:83)` 
`at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)` 
`at invokeEventListeners (ext:deno_web/02_event.js:801:5)`
`at dispatch (ext:deno_web/02_event.js:658:9)`

Why is it referencing your file .../gildas/...

**Comment by anotatta** [comment]
I want to add that if I let the program run to the end, even with the error, the program did produce the files to all the external links.  Not sure what the error is about.

**Comment by gildas-lormeau** [comment]
Sorry for the late answer, I tried to reproduce the issue on Windows (11) with the last version (2.0.47) but I was not able to do so. On my end, everyting works as expected. However, I recently fixed an issue related to the `--crawl-rewrite-rule` option so I might have fixed it. Can you tell me if you still encounter this issue with the last version?

**Comment by anotatta** [comment]
Works now.  Thanks.

**Comment by gildas-lormeau** [comment]
Thank you for the feedback!
