### ISSUE TITLE
Can't change infobar template

### ISSUE THREAD

**Issue by Vidanox** [gildas-lormeau/single-file-cli#109]
Hi, it seems like there is no way of customizing the actual infobar variables, as you could with the extension.
(chrome-extension://mpiodijhokgodhhofbcjdecpffjipkle/src/ui/pages/help.html#template-variables)

```
--include-infobar true 
```

**Comment by gildas-lormeau** [comment]
Thanks, I confirm that I had forgotten to define an option for this. It's fixed, the new option `--infobar-template` will be available in the next version.

**Comment by Vidanox** [comment]
Really appreciate it, thanks.
