### ISSUE TITLE
--error-file missing timestamps

### ISSUE THREAD

**Issue by emp-00** [gildas-lormeau/single-file-cli#110]
I'm using this option: --error-file="errorlog.txt"

See below an example of the errorlog.txt content in my case. I would be great if a timestamp could be saved as well, so that the user knows when the specific error had occurred. 

Example:
**[2024-08-01 08:13:22]** URL: https://en.wikipedia.org/wiki/Cloud_computing_architecture

Current format is just showing a URL (other errors also have no timestamp as far as I remember):
URL: https://www.nvidia.com/en-us/autonomous-machines/intelligent-video-analytics-platform/
URL: https://en.wikipedia.org/wiki/Cloud_computing_architecture
URL: https://www.cnbc.com/internet/
URL: https://www.cnbc.com/internet/
URL: https://en.wikipedia.org/wiki/Cloud_computing_architecture
URL: https://en.wikipedia.org/wiki/Cloud_computing_architecture

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I added the date in the log (in ISO format), the feature will be available in the next version.
