### ISSUE TITLE
When fully set to fully load page, single file downloads images as texts

### ISSUE THREAD

**Issue by takingurstuff** [gildas-lormeau/single-file-cli#112]
I was using an edited version of single file cli to download a site, i checked the downloaded page and they have no images in them
command used like follows
```
./single-file --browser-server=http://localhost:9226 --urls-file=./urls.txt --output-directory=/home/mac-sv/XBX/dl5 --errors-file=/home/mac-sv/XBX/threads5/logs/errors.log --browser-wait-until=networkIdle  --browser-wait-delay=1000 --max-parallel-workers=1
```

this is what single file downloaded
![Screenshot 2024-08-10 at 16 50 49](https://github.com/user-attachments/assets/cb1b1f1b-3ada-4064-bbf8-e255dc5ae2d4)
the original page it is supposed to download looks like this:
![Screenshot 2024-08-10 at 16 51 01](https://github.com/user-attachments/assets/48a789e5-15dc-4b9c-90a6-18b8619f9e4f)

I have set the signal to networkIdle because then everything will be loaded completed, i also added the delay as a failsafe in case the images still somehow failed to load, does this have something to do with the loadDeferredImages flag?

I changed it so that it scrolls after load to load some comments with the scroll

The edited version is avalaible at this fork:

[https://github.com/takingurstuff/single-file-cli](url)

**Comment by takingurstuff** [comment]
i launched it in headful and the resources downloaded and rendered properly. This happened on a Ubuntu remote machine i was running on. I did a few tests on my local mac machine and it turns out that pages downloaded with google chrome as a browser had all the images. So i just switched out the browser from chromium to google chrome on the linux machine, but the same still happened on linux. There was no problem with google chrome on macOS

**Comment by takingurstuff** [comment]
here are images of the page sources for more context
captured on linux:
![Screenshot 2024-08-13 at 15 46 42](https://github.com/user-attachments/assets/45d7613e-a79b-4e59-b45c-46260b236e82)
captured on mac:
![Screenshot 2024-08-13 at 15 53 00](https://github.com/user-attachments/assets/5c2fd517-8e3d-4df9-a2c8-d3e3057c4ed4)

both downloaded with same ver fo chrome in headful

the issue with the images happened on the highlighted lines

**Comment by takingurstuff** [comment]
just out of curiosity, which OS is single-file-cli tested on?

**Comment by gildas-lormeau** [comment]
That's a bit strange... 

On my end, I do my tests mainly on macOS, and Windows 11. I can also do some tests easily on Asahi Linux and WSL. I do not have an Ubuntu machine, but I can run tests in a VM.  At one time or another, I tested single-file-cli on all these environments.

**Comment by takingurstuff** [comment]
anyways, i found out the issue only happens when i use the browser server options instead of doing the internal launching.

what is the difference between connecting to an external chrome vs an internally launched chrome, because i tested single file with the external chrome and the image was not downloaded but internally launched chrome downloaded absolutely fine.

**Comment by gildas-lormeau** [comment]
Sorry for the very late reply, this might be related to the options used to launch Chrome, see https://github.com/gildas-lormeau/single-file-cli/a6207428307110b559c12fdb6731b5f33762e513/master/lib/constants.js#L24-L57 and https://github.com/gildas-lormeau/single-file-cli/a6207428307110b559c12fdb6731b5f33762e513/master/lib/browser.js#L39-L73
