### ISSUE TITLE
[question] <a> link href replace

### ISSUE THREAD

**Issue by iamqiz** [gildas-lormeau/single-file-cli#116]
how to replace link href ? 
for example , Suppose the website have http like this:
```
<html>
<body>
welcome to xxx
<a href="www.xxx.com/?id=music">  music </a>
<a href="www.xxx.com/?id=movie ">  movie </a>
</body>
</html>
```
in the final ouput html, I hope the href attribute is replaced with something others like this:

```
<html>
<body>
welcome to xxx
<a href="/music.html">  music </a>
<a href="/movie.html">  movie </a>
</body>
</html>
```

so that  those 2 links (music and movie) can be access locally
how to do that? 
thanks!

ps: 
my question is like this : https://github.com/gildas-lormeau/single-file-cli/issues/40
the difference is that I want a custom href replacement but that user want auto replacement

**Comment by gildas-lormeau** [comment]
It's fixed in the last version I've just published. See the option `--resolve-link`.
