### ISSUE TITLE
Fresh `npm` install of v2.0.58 fails with `Relative import path "simple-cdp" not prefixed with / or ./ or ../`

### ISSUE THREAD

**Issue by pirate** [gildas-lormeau/single-file-cli#118]
Steps to reproduce:
```bash
mkdir empty-dir && cd empty-dir

npm install single-file-cli
cd node_modules/single-file-cli

./single-file --version
```
```
To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
error: Uncaught Error: require() of ES Module /Users/squash/archivebox/data/node_modules/single-file-cli/single-file not supported. Instead change the require to a dynamic import() which is available in all CommonJS modules.
    at createRequireEsmError (node:module:752:15)
    at wrapSafe (node:module:709:13)
    at Module._compile (node:module:717:27)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
    at Object.loadCjsModule (ext:deno_node/02_init.js:64:22)
    at loadCjsModule ([ext:ext/node/lib.rs:761:29]:2:32)
    at [ext:ext/node/lib.rs:761:29]:3:7
```
<img width="844" alt="image" src="https://github.com/user-attachments/assets/4b2eb39d-025d-4c58-8fa8-597352d914ec">

Note I cannot do the suggested edit of `package.json` as we don't really have one. ArchiveBox runs in whatever data dir is provided by the user (which is usually a fresh empty dir, not a JS project dir with a package.json). We call `npm install ...` subcommands once during setup to produce a `node_modules` folder, then call binaries within it directly when we need them.

(It's worked fine historically with `single-file@1.1.54` and our other JS dependencies)

I've also gotten this error when trying to install in a different dir:
```bash
error: Relative import path "simple-cdp" not prefixed with / or ./ or ../
    at file:///Users/squash/Desktop/empty-dir/node_modules/single-file-cli/lib/cdp-client.js:28:30
```
<img width="948" alt="image" src="https://github.com/user-attachments/assets/2d692d32-47b0-4e4c-b777-70803f1e3899">

Versions:
- `npm --version`: `10.8.3`
- `node --version`: `22.6.0`
- `deno --version`: `1.45.5`

<img width="369" alt="image" src="https://github.com/user-attachments/assets/75a3002a-b4eb-4f21-9eb4-1dd842e85bdf">

**Comment by gildas-lormeau** [comment]
I think the best solution to this problem is to run single-file via `npx` in '/empty-dir'.

```sh
empty-dir % npx single-file --version
2.0.58
```
