### ISSUE TITLE
Option accept-language only works if option user-agent is used as well

### ISSUE THREAD

**Issue by marco-eckstein** [gildas-lormeau/single-file-cli#120]
I tried using the option `--accept-language de-DE,en-US` and got the error `Invalid parameters when calling Emulation.setUserAgentOverride({"acceptLanguage":"de-DE,en-US"})`. After some research, I found out that to fix this, I need to also pass the option `--user-agent myUserAgent`.

That is unfortunate, because I do not want to be bothered finding out the correct `user-agent` value, which depends on my installed Chrome version. At the very least, the description of option `accept-language` should note that `user-agent` is required.

Version: 2.0.59

**Comment by gildas-lormeau** [comment]
Thank you. Actually, the code took this constraint into account, but I'd made a mistake in the name of a property allowing to get the default user-agent. The bug is fixed, the fix will be available in the next version.

**Comment by marco-eckstein** [comment]
That was quick! Thanks! Confirmed to work in version 2.0.60.
