### ISSUE TITLE
Crawling doesn't work if you don't specify a custom crawl rewrite rule

### ISSUE THREAD

**Issue by TheBv** [gildas-lormeau/single-file-cli#126]
When running the following command
```
./single-file-x86_64-linux https://imgur.com --crawl-replace-URLs=true --crawl-links=true
```
I receive the following error
```
Cannot read properties of undefined (reading 'forEach')
```
Which is referring to this line of code https://github.com/gildas-lormeau/single-file-cli/blob/31c040feb7bf4facea3072502a2bf1190dd2abe8/single-file-cli-api.js#L231

From my understanding this is supposed to be an optional parameter?
If not it'd be great if it was :)

**Comment by gildas-lormeau** [comment]
Thank you very much for the report. I was able to reproduce and fix the bug. The fix will be available in the next version.
