### ISSUE TITLE
Skips First URL in the list of URLs

### ISSUE THREAD

**Issue by nitincodery** [gildas-lormeau/single-file-cli#13]
When using `--urls-file` option, it misses the First URL in the list.

Workaround: Add a empty line at start of the file.

This issue is present on [single-filez-cli](https://github.com/gildas-lormeau/single-filez-cli) too.

**Comment by nitincodery** [comment]
I tried looking at code and it seemed correct to me. I couldn't find why it is skipping First URL from list :(

**Comment by gildas-lormeau** [comment]
So, you are bot able to reproduce the issue anymore?

**Comment by nitincodery** [comment]
Yes, I'm not able to reproduce it anymore. Its weird, the other day it was always skipping First URL, but then yesterday with same input file it was working fine. Still, I added PR #14 with Microsoft Windows new-line regex if it was bugging due to that.
