### ISSUE TITLE
Browser user script not working

### ISSUE THREAD

**Issue by gemini0x2** [gildas-lormeau/single-file-cli#130]
Hi, 

I've always been unsuccessful trying to execute a user script using the provided [method](https://github.com/gildas-lormeau/SingleFile/wiki/How-to-execute-a-user-script-before-a-page-is-saved). For this reason used to directly include my script code inside the `single-file-cli/back-ends/webdriver-chromium.js` and everything worked as expected.

**webdriver-chromium.js (used to work)**
```js
if (options.url.includes("example.com") ) {
    var my_script_in_string = `
        var element = document.querySelector('.enter-gate__submit--yes');
	if (element) {
            element.click();
            console.log('successfully clicked enter button');
        } else {
            console.log('Error! enter button not found!');
        }`;
    await driver.executeScript(my_script_in_string);
}
```
But now that I updated to the latest version it appears that single-file got rid of webdriver-chromium.js, as the core implementation changed. So I can no longer use the method above.

Here below is the UserScript that I'm trying execute (same functionality as above), but nothing happens! Basically the script should click an "enter" button, when this action is performed the page loads the content. This should be done immediately after page loads and before capture. But when I check the saved html file I can see that the button was never clicked as the captured page still shows the button with no page content.

**singlefile-browser-script.js (Does not work!)**
```js
// ==UserScript==

(() => {
  dispatchEvent(new CustomEvent("single-file-user-script-init"));

  addEventListener("single-file-on-before-capture-request", () => {
    var currentURL = window.location.href;
    if (currentURL.includes("example.com")) {
      var element = document.querySelector('.enter-gate__submit--yes');

      if (element) {
        element.click();
        console.log('successfully clicked enter button');
      } else {
        console.log('Error! enter button not found!');
      }
    }
  });

  addEventListener("single-file-on-after-capture-request", () => {
    console.log("DONE!")
  });

})();
```

Note: My command
```shell
single-file https://example.com --browser-script "./singlefile-browser-script.js" --crawl-links=true --crawl-inner-links-only=true --crawl-max-depth=2
```

**Comment by gildas-lormeau** [comment]
Since I cannot test the page myself, can you add a `debugger` statement after `var element = document.querySelector('.enter-gate__submit--yes');`, launch single-file with the `--browser-debug` and remove `--crawl-` options, and debug the code?

**Comment by gemini0x2** [comment]
Hey, thanks for the quick reply. I will try adding the debugger. Does the debugger prints console.logs in the terminal?

**Comment by gemini0x2** [comment]
adding that option breaks single-file:
```shell
single-file https://example.com --browser-script "./singlefile-browser-script.js" --browser-debug
```

error:
```shell
file:///home/gemini/.nvm/versions/node/v20.18.0/lib/node_modules/single-file-cli/lib/deno-polyfill.js:87
                                                reject(new Error(`Process exited with code ${code}`));
                                                       ^

Error: Process exited with code 1
    at ChildProcess.<anonymous> (file:///home/gemini/.nvm/versions/node/v20.18.0/lib/node_modules/single-file-cli/lib/deno-polyfill.js:87:14)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:294:12)

Node.js v20.18.0
```

By the way I'm running in ubuntu server without any user interface so browser is launched as headless.

**Comment by gildas-lormeau** [comment]
You need indeed a display server to display the debugger. You can use `--console-messages-file` instead, it will allow you get the logs in the standard output.

**Comment by gemini0x2** [comment]
ok, I found whats causing the issue. Actually my command uses a few other options and removing the following option allowed the user script to be executed:
``` shell
--browser-args '["--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"]'
```
I will be closing this issue as it was solved!
@gildas-lormeau  thanks a lot for your help, using `--console-messages-file` will be very useful!

**Comment by gildas-lormeau** [comment]
You're welcome! FYI, I was not able to reproduce the issue related to `--browser-args`.
