### ISSUE TITLE
Per-URL output directory when using `--urls-file`

### ISSUE THREAD

**Issue by MirisWisdom** [gildas-lormeau/single-file-cli#133]
Hey Gildas,

How possible would it be to control the output directory for each URL when using `--urls-file`? For example, imagine `list-urls.txt` comprising the URL *and* output directory on the same line, probably delimited by a tab or something equivalent.

This would account for scenarios where we want to save pages to a directory structure which we already know in advance. At the moment, I'm manually invoking `single-file-cli` for each URL with the desired output directory; however, the lack of parallelism is evident.

No stress about implementing it -- I was mostly curious regarding the feasibility. I'd be happy to try implementing it if you have any pointers or things I should consider before going down the rabbit hole :)

---

Side-note: If there's an alternative approach that grants this control without sacrificing the speed, I'd be more than happy to give it a whirl! Is there a way of speeding up (subsequent) `single-file-cli` invocations?

**Comment by gildas-lormeau** [comment]
Thank you for the suggestion. I've implemented a way to pass the options for each URL. Thus, you'll be able to set a custom filename template to select the output directory, see the example below. This new feature will be available in the next version.

Example of URLs file
```
https://www.example.com --filename-template="/out1/example.html"
https://www.wikipedia.com --filename-template="/out2/%if-empty<{page-title}|No title> ({date-locale} {time-locale}).{filename-extension}"
```

**Comment by MirisWisdom** [comment]
Wow, that is magnificent - love the way you've implemented it by using the `--filename-template`; thank you very much Gildas!

**Comment by gildas-lormeau** [comment]
You're welcome! I've just published the new version.

**Comment by emp-00** [comment]
@gildas-lormeau : That's indeed a great new feature! Question: Does this work with all options and even with multiple options? We just have to put the options after the url all in the same line, that's it?

**Comment by gildas-lormeau** [comment]
Sorry for the late reply @emp-00, I confirm you can pass multiple options if you want. It should work exactly as you described.
