### ISSUE TITLE
Permission Error When Saving with Single-file to a Shared Network Drive

### ISSUE THREAD

**Issue by Yirenxs** [gildas-lormeau/single-file-cli#141]
**Description:**

I'm using single-file to save HTML files to a shared network drive located at \\192.168.2.22\Education. Although I have access to this shared drive (I can download files to it using urlretrieve), single-file throws a permission error.

**Python Code:**

```
show_dir = Path(r'\\192.168.2.22\Education')
show_dir.mkdir(exist_ok=True)

fname_html = show_dir / "{}.html".format(sanitize_filename(article["title"]))

if not fname_html.exists():
    if single_file_exec_path and cookie_file_path:
        command = [
            single_file_exec_path,
            "https://www.xxx.com.cn/article/"
            + article["article_id"],
            str(fname_html),
            "--browser-cookies-file=" + cookie_file_path
        ]
        logger.debug(f"singlefile command {command}")
        try:
            subprocess.run(command, check=True)
            print(f"Successfully {fname_html}")
        except subprocess.CalledProcessError as e:
            print(f"Failed to fetch page using single-file: {e}")
    else:
        print("single-file-exec-path or cookie-file-path is not provided.")
```

**Error Message:**

```Requires all access to "\\\\192.168.2.22\\Education\\XXX.html", specify the required permissions during compilation using `deno compile --allow-all` [2024-11-20T01:58:15.369Z] URL: https://www.xxx.com.cn/article/812525```

**Expected Behavior:**

I expect to be able to save the HTML file to the specified shared network drive path without errors.

**Environment:**

Operating System: windows 11
Python Version: Python 3.12.2
Single-file Version: v2.0.71

Thank you!

**Comment by gildas-lormeau** [comment]
Thank you, this issue is due to https://github.com/denoland/deno/issues/24703 in fact. I've implemented the suggested workaround (use `--allow-all` on Windows). It should be fixed in the version v2.0.72 I've just published.
