### ISSUE TITLE
singlefile-cli takes extremely long amounts of time on many websites

### ISSUE THREAD

**Issue by groby** [gildas-lormeau/single-file-cli#145]
Example: https://www.theblueground.com/ - running singlefile on this takes about 2 minutes 30 seconds.

```
time single-file  "--browser-executable-path=/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary" "--browser-args=[\"--headless\", \"--incognito\", \"--run-all-compositor-stages-before-draw\", \"--virtual-time-budget=9000\", \"--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 ArchiveBox/0.7.2 (+https://github.com/ArchiveBox/ArchiveBox/)\", \"--window-size=1920,1280\"]" "https://www.theblueground.com/" singlefile.html
``` 
results in
```
real	2m23.004s
user	0m13.003s
sys	0m2.898s
```

If I just pull the DOM via ```chrome-canary --headless --window-size=1920,1080 --run-all-compositor-stages-before-draw --virtual-time-budget=9000 --incognito --dump-dom  https://www.theblueground.com```, I spend ~7s until I've got the data, and another 8 until I've pulled in all dependent files via monolith

```time /Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary --headless --window-size=1920,1080 --run-all-compositor-stages-before-draw --virtual-time-budget=9000 --incognito --dump-dom  "https://www.theblueground.com/?utm_source=google&utm_medium=cpc&utm_campaign=USA_Brand_Sea_Adw_EN_Dom_All&utm_content=597324626802&utm_term=blueground&gclid=Cj0KCQiAjMKqBhCgARIsAPDgWlx0nVI3Oz44GVzfPtmHZyEXuoHi9zNhkNcnI_a6aA3wwAzz64ZLuRkaAluxEALw_wcB" | monolith - -I -b https://www.theblueground.com -o mvt
```
results in
```
real	0m13.178s
user	0m3.394s
sys	0m1.704s
```

And yes, single-file and monolith use very different approaches to resolve dependencies, but I'd be surprised that alone would cause an order of magnitude difference in execution speed.

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue when running the command below with the last version of single-file. It takes approx. 10 seconds to save the page. Can you tell me if you can reproduce the issue on your end when running this command?

```sh
./single-file "https://www.theblueground.com/" 
```

**Comment by groby** [comment]
Definitely massively faster, thanks. I'll try to track down which flag makes it cranky, but closing this one. (Since clearly issue on my end, not yours)

**Comment by groby** [comment]
Heh. I spoke too soon. It repros again, this time with a different URL. (The one I gave above still wraps in 12 seconds). Try https://www.zdnet.com/home-and-office/smart-office/using-the-wrong-usb-c-cable-can-damage-your-tech-heres-how-to-avoid-that/

From what I can tell via the debug messages, single-file spends about a minute starting up Chrome and then does the actual job of creating a single file in ~20 seconds. I.e.  the first message in the debug file ("Loading page about:blank") is about a minute after the process starts.

I've been doing some digging why that would take a minute, but not much success. (Tried stable and canary, tried new profiles - no changes. So probably not extensions or profile cruft)

Watching what gets started during that minute, Chrome is spawning an inordinate number of render processes - 75 total. 

I'll keep poking at this from my end, but if it triggers any thoughts for you which direction I should look, I'd appreciate it :)

**Comment by gildas-lormeau** [comment]
On my end, it takes approx. to save this page. What do you see in the `logs.txt`when running the command below? 

`./single-file https://www.zdnet.com/home-and-office/smart-office/using-the-wrong-usb-c-cable-can-damage-your-tech-heres-how-to-avoid-that/ --debug-messages-file=logs.txt`

**Comment by groby** [comment]
Here's the exact command line, with output
```
$ time ./single-file -"-browser-executable-path=/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary"   --debug-messages-file dmf  --errors-file er https://www.zdnet.com/home-and-office/smart-office/using-the-wrong-usb-c-cable-can-damage-your-tech-heres-how-to-avoid-that/

real	1m13.384s
user	0m25.453s
sys	0m11.460s
```

And here's the debug message file
```
[2025-01-26T01:35:10.100Z] Loading page about:blank
[2025-01-26T01:35:10.153Z] Bypassing CSP
[2025-01-26T01:35:10.256Z] Loading page https://www.zdnet.com/home-and-office/smart-office/using-the-wrong-usb-c-cable-can-damage-your-tech-heres-how-to-avoid-that/
[2025-01-26T01:35:10.293Z] Detecting top frame ID
[2025-01-26T01:35:10.558Z] Detecting lifecycle event DOMContentLoaded
[2025-01-26T01:35:10.559Z] Detecting lifecycle event firstMeaningfulPaintCandidate
[2025-01-26T01:35:10.559Z] Detecting lifecycle event firstContentfulPaint
[2025-01-26T01:35:10.559Z] Detecting lifecycle event firstPaint
[2025-01-26T01:35:10.559Z] Detecting lifecycle event firstImagePaint
[2025-01-26T01:35:12.146Z] Detecting lifecycle event load
[2025-01-26T01:35:13.064Z] Detecting lifecycle event networkAlmostIdle
[2025-01-26T01:35:13.064Z] Waiting 1000 ms
[2025-01-26T01:35:13.064Z] Detecting lifecycle event firstMeaningfulPaint
[2025-01-26T01:35:14.066Z] Detecting page ready
[2025-01-26T01:35:14.066Z] Getting execution context
[2025-01-26T01:35:14.078Z] Capturing page
[2025-01-26T01:35:21.285Z] Setting page data
[2025-01-26T01:35:21.286Z] Returning page data
[2025-01-26T01:35:21.286Z] Closing page
```

As I said - a missing minute. Once you got about:blank, single-file is actually using 11 seconds. I'll be darned if I know what happens in the whole minute before that. No extensions installed that could keep it from starting up at a decent speed.

**Comment by groby** [comment]
Just for grins, also shut down all other Chrome instance - doesn't make a difference either.

In that minute of silence, it's spinning up 70+ Chrome Renderer processes. I'm curious, are you running on macOS, or might this be an OS-specific thing?

**Comment by brasswood** [comment]
> It looks like `single-file` cannot close the tab or the browser immediately for some reason.

I think this might be the root cause: https://github.com/denoland/deno/issues/27112

I just had `single-file` hang, and when I terminated it, it printed this error:

```
error: Uncaught (in promise) TypeError: Child process has already terminated
                child.kill();
                      ^
    at ChildProcess.kill (ext:deno_process/40_process.js:371:13)
    at closeBrowser (file:///home/andrew/single-file-cli/lib/browser.js:115:9)
    at closeBrowserAndExit (file:///home/andrew/single-file-cli/single-file-launcher.js:137:8)
    at loop (ext:deno_os/40_signals.js:77:7)
```

**Comment by brasswood** [comment]
Actually I'm wrong, that's not at all why it's hanging up. It still probably wouldn't hurt to wrap that in a try/catch block, though.
