### ISSUE TITLE
where to set ignoreHTTPSErrors config

### ISSUE THREAD

**Issue by 404name** [gildas-lormeau/single-file-cli#20]
> [Options should not be hardcoded, especially when they have an impact on security. So, the value should come from `options` and **MUST NOT** be set to `true` by default](https://github.com/gildas-lormeau/single-file-cli/pull/5)

> _Originally posted by @gildas-lormeau in https://github.com/gildas-lormeau/single-file-cli/pull/5#discussion_r920616749_

When I download a website with an expired SSL certificate, it is effective to manually modify the code as above.。

I don't seem to see the entry for setting 'ignoreHTTPSErrors' in the [current version](https://github.com/gildas-lormeau/single-file-cli/blob/master/back-ends/puppeteer.js#L71). Is it necessary to add a set entry like this?
```
  if (options.ignoreHTTPSErrors !== undefined) {
    browserOptions.ignoreHTTPSErrors = options.ignoreHTTPSErrors;
  }
```

**Comment by gildas-lormeau** [comment]
Where did you read that `ignoreHTTPSErrors` could be a valid option?

**Comment by 404name** [comment]
> Where did you read that `ignoreHTTPSErrors` could be a valid option?

single-file-cli doesn't work when I download a website with an expired SSL certificate. I directly modify the source code   so that will take effect just like [#5 ](https://github.com/gildas-lormeau/single-file-cli/pull/5#discussion_r920616749) `add browserOptions.ignoreHTTPSErrors=true` . But you close it as you say `Options should not be hardcoded, especially when they have an impact on security. So, the value should come from options and MUST NOT be set to true by default`

```
- const browserOptions = {};
+ const browserOptions = {
+	ignoreHTTPSErrors: true
+ }
```
So now if I don't modify the code, I can't download the website with expired ssl. I can't find the entry of single-file-cli to ignore the SSL certificate error, so I raise an issue to ask if it is ignored, or there is a place to set it just I did not see it.

**Comment by gildas-lormeau** [comment]
Thank you for the additional info, I just pushed the support of the new option `browser-ignore-insecure-certs`. It should work fine with all back-ends used by the CLI.
