### ISSUE TITLE
How can I use docker cli instead of curl with cookie.json?

### ISSUE THREAD

**Issue by pJahad** [gildas-lormeau/single-file-cli#25]
There is a website I can download html using curl only with  `-H 'cookie: ghost-members-ssr=example; ghost-members-ssr.sig=example'`.

For single-file-cli, I prepare the json file
`echo '{"ghost-members-ssr": "example", "ghost-members-ssr.sig":"example"}' > cookie.json`
and **mount this file into docker**.

However, when I run the cli with option `--browser-cookie-file="/usr/src/app/node_modules/single-file-cli/cookie.json"` , the result html file is not changed from without the option.

How can I use docker cli instead of curl with cookie.json?

**Comment by pJahad** [comment]
I tried re-creating the json, but it still failed.
Is there a way to debug whether the authentication is working correctly?

**Comment by pJahad** [comment]
I typo'd `browser-cookie-file` and it was correctly `browser-cookies-file`.
I was able to confirm that it works correctly with docker as well as CLI.
Thanks for your kind support.

**Comment by gildas-lormeau** [comment]
You're welcome!
