### ISSUE TITLE
Recent tagged Docker image?

### ISSUE THREAD

**Issue by turian** [gildas-lormeau/single-file-cli#32]
I'm curious when you will release a new Docker tag.

From discussion on archivebox, I see that newer chromium versions are breaking some functionality. So I don't want to rely upon latest tag which might break later.

However, I also don't want to use a very old version of single-file.

Could you tag a new release that appears stable, possibly with a particular chromium version in case local users need to rebuild the docker image?

**Comment by gildas-lormeau** [comment]
I just released a new tagged image, see https://hub.docker.com/layers/capsulecode/singlefile/v1.0.33/images/sha256-c116b99f8f5b15eaad522190c32091ccc27e4d6dded6fc99ef4bc4de8b2aa835?context=repo.
