### ISSUE TITLE
Set Chrome profile for puppeteer when using CLI

### ISSUE THREAD

**Issue by beefdrifter** [gildas-lormeau/single-file-cli#38]
**Is your feature request related to a problem? Please describe.**
When SingleFile CLI saves a page with puppeteer, the page is saved without any of the familiar extensions your personal Chrome profile uses (for example, ad blockers), because puppeteer runs on a clean profile by default.

**Describe the solution you'd like**
Would it be possible to add an argument that points to a Chrome profile folder for the CLI? It would allow the page to be saved the way you would normally see it when you're using Chrome, with extensions and all. Thanks!

**Comment by gildas-lormeau** [comment]
This issue is now obsolete.
