### ISSUE TITLE
Add an option to import settings from browser when using cli

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/single-file-cli#45]
**Describe the solution you'd like**
Support import browser exported settings file `singlefile-settings.json` to cli config.

The option name may :
--browser-settings-file
Description:
Overwrite the default settings of cli by the settings file exported from the browser plugin.

**Comment by kimoch111** [comment]
This issue was proposed three years ago, why haven't I seen this parameter in the options ?When will it be released?

**Comment by gildas-lormeau** [comment]
Thank you for the reminder, it's implemented.
