### ISSUE TITLE
TypeError: window.singlefile is undefined

### ISSUE THREAD

**Issue by scruel** [gildas-lormeau/single-file-cli#46]
**Describe the bug**
Could not save page and got TypeError.

**To Reproduce**
Following command works fine:
`single-file  https://www.baidu.com 1.html --back-end=webdriver-gecko  --browser-headless=false`

But not this:
`single-file  https://baidu.com 1.html --back-end=webdriver-gecko  --browser-headless=false`
Will got error:
```
TypeError: window.singlefile is undefined URL: https://baidu.com
Stack: undefined
```

**Expected behavior**

**Environment**
 - OS: Win10 Pro
 - Browser: Firefox 94
 - geckodriver v0.30.0

**Comment by gildas-lormeau** [comment]
This issue is now obsolete.
