### ISSUE TITLE
support for web pages with charset gbk

### ISSUE THREAD

**Issue by GitHubUserC** [gildas-lormeau/single-file-cli#47]
could you please add support for web pages with charset gbk, currently when saving web pages with charset gbk the code is messed up.

test url: https://www.52pojie.cn/

**Comment by gildas-lormeau** [comment]
I cannot reproduce the issue. Do you pass any particular options when calling `single-file`?

**Comment by GitHubUserC** [comment]
no particular options, I use docker.

docker run -v $(pwd):/usr/src/app/out singlefile "https://www.52pojie.cn/" single-file-cli.html

[single-file-cli.zip](https://github.com/gildas-lormeau/single-file-cli/files/12328830/single-file-cli.zip)

but if I use web extension.

[single-file.zip](https://github.com/gildas-lormeau/single-file-cli/files/12328835/single-file.zip)

It can be clearly seen that all Chinese characters in the CLI version of the saved file (single-file-cli.zip) have become unrecognizable, which is already known to be https://www.52pojie.cn/ contains <meta http-equiv="Content-Type" content="" text/html; charset=gbk" />, but the web extension works fine, and the Chinese characters in the saved file (single-file.zip) are displayed normally.
