### ISSUE TITLE
Output extension should be .zip if `--compress-content --self-extracting-archive false` is used

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/single-file-cli#52]
`--compress-content --self-extracting-archive false` outputs a zip file, but it receives the extension `.html` rather than `.zip`

**Comment by gildas-lormeau** [comment]
Note that you can use the option `--filename-template` to replace `.html` with `.zip`. As a general rule, I'm not a fan of "self-magical" behavior, but if the need really exists, I'm not against giving it some thought.

**Comment by gildas-lormeau** [comment]
It's fixed in the latest version via the new template variable `{filename-extension}`.
