### ISSUE TITLE
Can we use sessionData in CLI?

### ISSUE THREAD

**Issue by DeployThemAll** [gildas-lormeau/single-file-cli#54]
I'm using Cli with cookies 

I need to include sessionData and also open the browser in stealth mode.

I use stealth mode plugin with puppeteer along with adding sessionData and works fine. I just can't include them while using SingleFile Cli?

any idea on how to use it?

**Comment by gildas-lormeau** [comment]
Well, for some reason, I cannot convert the issue.

**Comment by DeployThemAll** [comment]
can you try downloading this page in cli and let me know the result

https://cxl.com/blog/which-color-converts-the-best/

You may have a better option

**Comment by gildas-lormeau** [comment]
You can now pass easily the path to your user data folder with the switch `--user-data-dir`, e.g. `./single-file https://www.example.com --browser-arg="--user-data-dir=/Users/<username>/Library/Application Support/Google/Chrome"` (on macOS).
