### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by ImportTaste** [gildas-lormeau/single-file-cli#59]
Forgive me if I've asked this before in one of the other repos (I did look but could've missed it), but is there a changelog I can look at anywhere? I want to know what's changed since I last updated single-file-cli and it doesn't seem like there's a very easy way to do that.

**Comment by gildas-lormeau** [comment]
Unfortunately, I'm too lazy to maintain a changelog for SingleFile CLI. I'd have to maintain one. Ideally, I'd like to do it when it's finished :)

Most of the time, I'm just updating the "core" module though. So, you can still have a look at the commits here: https://github.com/gildas-lormeau/single-file-core/commits/main. It's a bit technical but I include links to issues/discussions when available into the commit message.

**Comment by gildas-lormeau** [comment]
The changelog is now available in the releases page, see https://github.com/gildas-lormeau/single-file-cli/releases
