### ISSUE TITLE
Docker image architecture

### ISSUE THREAD

**Issue by rutkai** [gildas-lormeau/single-file-cli#65]
Hey,

I wanted to use the docker image from this repo and I needed to realize, that the most recent build is for arm only on Dockerhub:
![image](https://github.com/gildas-lormeau/single-file-cli/assets/1587720/ef412539-630e-42cd-915c-3f7b2b339eaa)

Is this intentional? I can see an old tag that is amd64. If you switched architecture, can I expect an official amd64 build or I should build it myself?

**Comment by gildas-lormeau** [comment]
Sorry, it was not intended, I've just pushed an image for amd64.

**Comment by rutkai** [comment]
Awesome, thanks!

**Comment by rutkai** [comment]
Sorry @gildas-lormeau, but one more thing: are you planning to update npmjs also? I noticed you created the version 2.0.0 but it is not there yet: https://www.npmjs.com/package/single-file-cli

**Comment by gildas-lormeau** [comment]
@rutkai I don't know. Since the new CLI relies on Deno, it will be less relevant. Note however that I can provide executable files now (see Releases page).

**Comment by rutkai** [comment]
@gildas-lormeau Deno seems to be using npm (through a CDN proxy, ESM) and I cannot depend on `single-file-cli` without you publishing it as a module. It doesn't support setting a dependency as a git repository.

More docs: https://docs.deno.com/runtime/manual/basics/import_maps

**Comment by gildas-lormeau** [comment]
The problem is that the new version on NPM wouln't be compatible with Node.js.

**Comment by gildas-lormeau** [comment]
I made the code compatible with Node. The version 2..x is now on NPM.
