### ISSUE TITLE
dns error: failed to lookup address information

### ISSUE THREAD

**Issue by yfiua** [gildas-lormeau/single-file-cli#66]
Hi,

I tried to run [single-file-cli](https://github.com/gildas-lormeau/single-file-cli). Both from dockerhub and git repo build I got the same error:

`docker run singlefile "https://www.wikipedia.org"`

error: Import 'https://registry-staging.deno.com/@std/path/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@std/path/meta.json): error trying to connect: dns error: failed to lookup address information: Name does not resolve
    at file:///usr/src/app/single-file-cli-master/single-file-cli-api.js:26:25

It seems it cannot load the json file from deno as the link is broken.

Do you have any idea? Thanks!

**Comment by gildas-lormeau** [comment]
It looks like it's a bug related to Deno but apparently it's fixed in the last versions, see https://github.com/denoland/deploy_feedback/issues/612

**Comment by rutkai** [comment]
I tracked this down as I'm struggling with this for hours now. It won't be updated for a while as
* Package `deno` comes from alpine registry: https://github.com/Zenika/alpine-chrome/blob/master/with-deno/Dockerfile#L4
* And alpine has an old `deno` build: https://pkgs.alpinelinux.org/packages?name=deno&branch=v3.19&repo=&arch=&maintainer=

And god knows when it's going to be updated.

**Comment by gildas-lormeau** [comment]
Thank you for the additional info, I guess the executable files from in the Releases page should not suffer from this issue though.

**Comment by yfiua** [comment]
Release works fine.

**Comment by gildas-lormeau** [comment]
I made the code compatible with Node.js and published a new version on Docker Hub based on Node.js instead of Deno.

**Comment by rutkai** [comment]
Thanks. May I know what's the long term plan here? Staying on deno (and switching back to it once this bug is fixed in the upstream image) or keeping both on the long run?

**Comment by gildas-lormeau** [comment]
The long plan should be to stay on deno once the bug is fixed. However, I will do my best to make the code compatible with Node.js though.
