### ISSUE TITLE
Executable alias doesn't work for global install

### ISSUE THREAD

**Issue by prurigro** [gildas-lormeau/single-file-cli#70]
When you run `npm install -g single-file-cli` it installs `~/.node/lib/node_modules/single-file-cli` and creates a symlink for `~/.node/lib/node_modules/single-file-cli/single-file` @ `~/.node/bin/single-file-cli`, but when you run it you get the following error:

```
error: Module not found "file:///home/prurigro/.node/bin/single-file-cli-api.js".
    at file:///home/prurigro/.node/bin/single-file-cli:26:44
```

Running `~/.node/lib/node_modules/single-file-cli/single-file`  works however, and creating an alias for that works as well:

```
alias singlefile='~/.node/lib/node_modules/single-file-cli/single-file'
```

**Comment by gildas-lormeau** [comment]
Thank you, this bug will be fixed in the next version.

**Comment by gildas-lormeau** [comment]
The new version 2.0.11 is available on NPM.

**Comment by prurigro** [comment]
Awesome, thanks so much for the quick fix! Not to mention for the amazing tool :)
