### ISSUE TITLE
It's just a long string of numbers

### ISSUE THREAD

**Issue by Explosion-Scratch** [gildas-lormeau/single-file-cli#74]
When I run something like `singlefile --compress-content --compress-HTML --compress-CSS --self-extracting-archive true https://example.com` I just get a HTML file with tons of numbers separated by commas

[Example Domain (3_28_2024 10_44_52 AM).u.zip.html.txt](https://github.com/gildas-lormeau/single-file-cli/files/14792117/Example.Domain.3_28_2024.10_44_52.AM.u.zip.html.txt)

(I've renamed the file to include .txt to get GitHub to upload it)

**Comment by Explosion-Scratch** [comment]
It seems like it's writing the Buffer as a string somehow, because `writeFileSync("output.html", Buffer(readFileSync("input.html", "utf-8").split(',').map(i => parseInt(i, 10)))` works

**Comment by gildas-lormeau** [comment]
Thank you, I was able to reproduce and fix the two bugs. The fix is available in the version 2.0.15 I've just published.

**Comment by Explosion-Scratch** [comment]
Awesome, tysm!
