### ISSUE TITLE
--back-end option doesn't seem to exist

### ISSUE THREAD

**Issue by sissbruecker** [gildas-lormeau/single-file-cli#75]
I tried running the following command from the README:
```
single-file https://www.wikipedia.org wikipedia.html --back-end=webdriver-gecko
```

That results in it just printing the help text, probably because the `--back-end` option isn't recognized. It works without that option.

I've been using this release: https://github.com/gildas-lormeau/single-file-cli/releases/download/v2.0.18/single-file-aarch64-apple-darwin

**Comment by gildas-lormeau** [comment]
Thank you, in fact this switch no longer exists since version 2.x, which no longer relies on puppeteer, selenium or playwright.

**Comment by sissbruecker** [comment]
Thanks, I figured after reviewing the recent changes. Was looking for some way to avoid shipping a Chromium installation in a Docker image by using the old jsdom backend. But Chromium will give more reliable results anyway, the size of the image is not as important. It's working great so far, thanks for your efforts here.
