### ISSUE TITLE
Error: Execution context not found

### ISSUE THREAD

**Issue by sissbruecker** [gildas-lormeau/single-file-cli#80]
This error occurs quite often for several URLs that I've tried:
```
Execution context not found URL: https://www.youtube.com/watch?v=F47WWw5ztvk
Stack: Error: Execution context not found
    at onTopFrameNavigated (file:///Users/sascha/dev/sandbox/single-file-cli/lib/cdp-client.js:194:12)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Connection.onFrameNavigated (file:///Users/sascha/dev/sandbox/single-file-cli/lib/cdp-client.js:181:7)
```

When it occurs, single-file can stall indefinitely and never exits. Doesn't happen consistently though.

It seems what these URLs have in common is that they redirect to some other URL after loading in the browser:
- https://www.youtube.com/watch?v=F47WWw5ztvk (redirects to a page stating video is not available anymore)
- https://gitlab.com/andrewbanchich/forty-jekyll-theme (redirects to a login page)
- https://www.armedangels.de/ (redirects to https://www.armedangels.com/de-de)

There's also this URL which doesn't have a redirect, but results in the same error:
- https://docs.github.com/de/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by sissbruecker** [comment]
Related to this, I've opened https://github.com/gildas-lormeau/single-file-cli/pull/79, which would allow an application running single-file as a sub-process to properly terminate it after a timeout. Even if the above issues can be fixed, I'd still suggest to have something like that in place, so that other tools using single-file have some reliable way of shutting it down if it doesn't respond for whatever reason.

**Comment by gildas-lormeau** [comment]
Thank you, this was actually a regression because retrieving the context ID of of single-file is harder than I expected.

**Comment by sissbruecker** [comment]
Thanks, seems to work fine now 👍
