### ISSUE TITLE
Add support for loading browser extensions

### ISSUE THREAD

**Issue by sissbruecker** [gildas-lormeau/single-file-cli#83]
One thing I'd like to be able to do is run single-file together with a Chrome extension like uBlock Origin, so that:
- the saved HTML doesn't contain any ads
- with some tweaking of uBlock0, it also removes cookie consent banners

Traditionally running extensions in headless Chrome was not possible, however somewhat recently a new headless mode was introduced that allows you to do pretty much anything you can do with a headful (?) Chrome instance, such as running extensions: https://developer.chrome.com/docs/chromium/new-headless

Adding support for this would require two configuration options:
- Allow using `--headless=new` instead of `--headless`
- Allow removing the `--disable-extensions` browser arg that single-file applies by default

I did try patching single-file-cli with these changes, and was able to get the extension loaded (requires an up-to-date Chromium as well). While I can deploy my app with a patched version of single-file, it would be great if this could be added to the core. I'm up for contributing these changes if we can align on an API / specific option naming.

**Comment by gildas-lormeau** [comment]
Thank you, I applied the suggested changes but I did not change `--headless` to `--headless=new` because it breaks the support of iframes (tested with https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe).

**Comment by sissbruecker** [comment]
Thanks! Can confirm that overriding the `--headless` option works now. That should be enough to get me started.

That iframe issue is a bit worrying, maybe I'll have to make using the extension optional. Let's see.

**Comment by gildas-lormeau** [comment]
For the record, I've looked at what's wrong with using `--headless=new`. In fact, this problem can also be reproduced by not launching Chrome in headless mode. For some reason that escapes me as I write this reply, `window.postMessage()` does not work as expected. At worst, it should be possible to emulate it or rely on an alternative API that would only be used when single-file-core is used by single-file-cli.

Translated with DeepL.com (free version)

**Comment by gildas-lormeau** [comment]
For the record, the frame issue is fixed in the version `v2.0.32`.

**Comment by sissbruecker** [comment]
It does work now, thanks for following up on that. In general, using single-file with the new headless mode seems to work very well, haven't observed any other issues so far.

**Comment by gildas-lormeau** [comment]
@sissbruecker Thank you for the feedback
