### ISSUE TITLE
error: Uncaught (in promise) Error: The process cannot access the file because it is being used by another process. (os error 32)

### ISSUE THREAD

**Issue by ashiflett0** [gildas-lormeau/single-file-cli#92]
The single-file-cli hangs after converting several links to html. I CTRL+C to stop the process and see the following error message:

error: Uncaught (in promise) Error: The process cannot access the file because it is being used by another process. (os error 32): remove 'C:\Users\FORENS~1\AppData\Local\Temp\56d1091bd37c4771'
    at async Object.remove (ext:deno_fs/30_fs.js:260:3)
    at async closeBrowser (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/lib/browser.js:120:3)
    at async closeBrowserAndExit (file:///Users/gildas/Desktop/Dev/project-single-file/single-file-cli/single-file-launcher.js:122:2)

Any ideas what's causing this?

**Comment by gildas-lormeau** [comment]
For the moment, it's not clear to me why this error is occurring. When the problem occurs, do you notice that there are still Chrome-related processes in the task manager?

**Comment by ashiflett0** [comment]
Yes, MS Edge processes are still running in the task manager. I have tried using different browsers such as Chrome and Chromium, and am still having the same issue.

**Comment by gildas-lormeau** [comment]
Thank you, this means that the program can't stop the browser for some reason. Do you run multiple `single-file` commands in parallel?

**Comment by ashiflett0** [comment]
No, I am running just one instance of single-file-cli in Powershell 7 (admin). My commands are:

.\single-file.exe --urls-file C:\Users\xx\Desktop\URLs.txt --output-directory C:\Users\xx\Desktop\temp  --save-original-URLs --browser-executable-path "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"

**Comment by gildas-lormeau** [comment]
I did a test with a list of 50 URLs but I wasn't able to reproduce the issue. When this bug occurs, are all the URLs in the list correctly saved?

**Comment by ashiflett0** [comment]
Yes, they all appear to be properly formatted URLs. Here is the list of URLs I was using.

[URLs.txt](https://github.com/user-attachments/files/15560984/URLs.txt)

**Comment by gildas-lormeau** [comment]
Thank you for your help, I was able to find the cause of the problem. The fix is available in the new version I've just published.
