### ISSUE TITLE
--browser-server is being ignored

### ISSUE THREAD

**Issue by m3nadav** [gildas-lormeau/single-file-cli#93]
I tried to use --browser-server to reuse a running browser but the argument did nothing, I found that the part of the code that is supposed to use the browser-server argument is trying to use `browserRemoteDebuggingURL` instead.
Opening a PR with suggested changes, hope it helps

**Comment by gildas-lormeau** [comment]
Thanks a lot for the PR, I can confirm that I had probably missed a regression during a refactoring.
